### ISSUE TITLE
Tabla locales_creature_text

### ISSUE THREAD

**Issue by tortosi** [Eragoneswow2/EsWoW2#1]
Como ya habrás visto, la tabla **locales_creature_text** ha cambiado a **creature_text_locale**.

He adaptado la sql para que añada los textos, aunque seguro que la forma de aplicarla no es la más correcta. 
He hecho esta sql: 
`REPLACE INTO `creature_text_locale` VALUES ('34965','0','0','esES','¡No puedes detener a los Kvaldir!');`

Si te interesa, tienes el archivo en la rama de mi repositorio. Por supuesto puedes modificarlo o hacer lo que necesites.

**Comment by tortosi** [comment]
Algunas de las tablas que han cambiado la estructura, al inyectar la sql no da error, pero tampoco aplica cambios en las tablas. La rectificación que he hecho arriba, no está nada bien hecha según los estándares de Trinitycore por lo que he visto. 
La última modificación que he hecho, ha sido la del templo de Ahn'Qiraj y he seguido la siguiente estructura:
`DELETE FROM `creature_text_locale` WHERE `CreatureID`='15277' AND `Locale`='esES';

INSERT INTO `creature_text_locale` (`CreatureID`, `GroupID`, `ID`, `Locale`, `Text`) VALUES
('15277','0','0','esES','¡%s entra en frenesí!');`

Mira si te gusta más esta y quieres aprovecharla para hacer las modificaciones. Está en mi repositorio.

Mañana cambiaré las que tengo ya hechas y revisaré el resto.

En ningún caso quiero rectificarte!! Quede claro que tan solo quiero colaborar.

Saludos.

**Comment by Eragoneswow2** [comment]
Buenas tortosi!

Pues la verdad es que de todo lo que he subido en este repo ya lo tengo todo actualizado a la nueva sintaxis que ha añadido TC en sus loc_xxx, así que sin problemas! A mi el uso del DELETE y del INSERT no me gusta, prefiero usar UPDATE que simplemente modifica el contenido de columna sin alterar la entrada en cuestión, evitando problemas de duplicidad o pérdida de textos si se da el caso de cambios de ID y haciéndolo mucho más manejable! 
Cuando se trata de traducir en base a algo, muchas veces se cambian los textos base o se editan los identificativos, y usar el DELETE/INSERT te puede llevar a perder contenido que no se asocia a ello en su origen.

Para trabajar, a mi me va perfecto así! Si quieres modificar tu los archivos finales con la estructura que sigues ahora, perfecto! No hay problema tortosi! Yo seguiré con el plan actual de traducciones por hacer, y te dejo gestionar todo lo es la implementación a ti.

PD. Cuando dices que al implementar los archivos no se producen cambios, es por que si no tienes puestas las traducciones que sacamos en las raleases de EsWoW2, no te añadirá las entradas y por lo tanto el UPDATE no tendrá efecto alguno. 
En EsWoW2 al principio de cada sql-loc_tabla añadíamos la siguiente linea:

INSERT IGNORE INTO `creature_text_locale` (`CreatureID`,`GroupID`,`ID`) SELECT `CreatureID`,`GroupID`,`ID` FROM `creature_text`;

Así en esta actualizada a la actual sintaxis, ya puedes trabajar con UPDATE sin problemas.

**Comment by tortosi** [comment]
Por lo que entiendo, primero debo insertar las traducciones que utilizábamos antiguamente?
Yo ya no las introducía al estar implementadas en las bases de datos de Trinitycore.

**Comment by Eragoneswow2** [comment]
No hace falta introducirlas si no se tienen, ya que con un command como el que te he puesto al final del mensaje, por ejemplo, puedes coger las columnas de la creature_text en este caso y ponértelas en las creature_text_locale, con lo que al tener las entradas ya dentro de la tabla puedes ir añadiendo la información con los UPDATE. Rápido y limpio.
