### ISSUE TITLE
Que hace esto exactamente

### ISSUE THREAD

**Issue by IlPicasso** [Eragoneswow2/EsWoW2#3]
Hola! Esto se ve genial, soy nuevo en la comunidad de trinityCore y quiero instalar un WoW 3.3.5a para mi comunidad

Para usar esto que debo hacer?

**Comment by Eragoneswow2** [comment]
Buenas IlPicasso! Lo que hace es traducir la base de datos de TrinityCore al español. Si desconoces un poco este mundo, te recomiendo que esperes. Céntrate en aprender con el servidor y luego ya irás toqueteando tablas, ya que esta sintaxis que voy añadiendo en mis lineas no es la ideal y hay que ir modificando su contenido.

**Comment by IlPicasso** [comment]
En todo caso, con esto puedo traducir mi servidor? Cuando estara estable o listo, algun ETA?
